### ISSUE TITLE
Gtags not works

### ISSUE THREAD

**Issue by rivalak** [XiongGuiHui/My-Linux-config#9]
1  I have the gtags been installed.    
2  I have added the tags layer and gtags.vim plugin.   
>  when I use SPC m g d with a c symbol, I got this fault.  
![image](https://user-images.githubusercontent.com/42036026/53157186-ebc30200-35fb-11e9-934a-6d57d5515342.png)
> Gtags for pattern: write_listError detected while processing function gtags#global[24].
.<SNR>231_ExecLoad:
line   27:
E344: Can't find directory "/home/rivalak/.cache/SpaceVim/tags/_home_rivalak_Workspace_
Projects_TodoList_src_" in cdpath
E472: Command failed
Press ENTER or type command to continue

**Comment by Martins3** [comment]
Firstly, cscope and gtags are two different tools. I am not familiar with cscope because I think gtags it's more powerful. You should install latest gtags instead of cscope.

Secondly,  you should understand the work flow of gtags.
1. generate gtags database
2. query the database
3. if you edit the source file in your project, if you should update the database

The Gtags layer of SpaceVim make these steps automatically.
The problem you encounter is that hadn't generate the database.
![image](https://user-images.githubusercontent.com/16731244/53162372-d8696400-3606-11e9-8ad0-67665f5ee9ba.png)

There is something worth mentioned:
1. gtags.vim is one part of gtags layer, there is no need to install gtags.vim specially.
2. I remap some key binding, you can read the autoload/myspacevim.vim for details.

**Comment by rivalak** [comment]
Ok, it works well now. And I have a question about how to jump back.

**Comment by rivalak** [comment]
> Firstly, cscope and gtags are two different tools. I am not familiar with cscope because I think gtags it's more powerful. You should install latest gtags instead of cscope.
> 
> Secondly, you should understand the work flow of gtags.
> 
> 1. generate gtags database
> 2. query the database
> 3. if you edit the source file in your project, if you should update the database
> 
> The Gtags layer of SpaceVim make these steps automatically.
> The problem you encounter is that hadn't generate the database.
> ![image](https://user-images.githubusercontent.com/16731244/53162372-d8696400-3606-11e9-8ad0-67665f5ee9ba.png)
> 
> There is something worth mentioned:
> 
> 1. gtags.vim is one part of gtags layer, there is no need to install gtags.vim specially.
> 2. I remap some key binding, you can read the autoload/myspacevim.vim for details.

Ok, it works well now. And I still have a question about how to jump back.

**Comment by Martins3** [comment]
1. what do you mean by **just back** ?
2. where is the document of CTRL + t ?

**Comment by rivalak** [comment]
> 1. what do you mean by **jump back** ?
> 2. where is the document of CTRL + t ?

This solves my question. [Vim common operations](https://anson2416.github.io/posts/15d5d397/).   
Thanks ! @Martins3
